import { defineStore } from "pinia";
import type { AnalyticsDto, CountryDto, PaymentTransactionDto, PlanDto, ScanDto, SubscriptionDto, WasteRecordDto } from "@resort/contracts";
import { api,isNetworkError } from "./api";

const emptySubscription=():SubscriptionDto=>({plan:"FREE",weeklyLimit:10,used:0,remaining:10,weekStart:"",resetsAt:""});
const emptyAnalytics=():AnalyticsDto=>({totalAccepted:0,totalWeightGrams:0,totalDisposalCo2eKg:0,recordsWithoutCarbonFactor:0,daily:[],dailyCounts:[0,0,0,0,0,0,0],categories:[],suggestions:[]});
const apiRelativePath=(path:string):string=>path.startsWith("/api/v1/")?path.slice("/api/v1".length):path;

export const useResortStore=defineStore("resort",{
  state:()=>({apiOnline:true,aiMode:"unknown" as "unknown"|"mock"|"openai",initialized:false,loading:false,previewUrl:"",file:null as File|null,scanRequestKey:"",scan:null as ScanDto|null,record:null as WasteRecordDto|null,countries:[] as CountryDto[],selectedCountryCode:"DE",subscription:emptySubscription(),plans:[] as PlanDto[],transactions:[] as PaymentTransactionDto[],history:[] as WasteRecordDto[],analytics:emptyAnalytics()}),
  actions:{
    async initialize(force=false){if(this.initialized&&!force)return;this.loading=true;try{const [subscription,records,analytics,countries,plans,transactions,health]=await Promise.all([api.get<SubscriptionDto>("/subscriptions/current"),api.get<{items:WasteRecordDto[]}>("/waste-records?pageSize=100"),api.get<AnalyticsDto>("/analytics/summary"),api.get<CountryDto[]>("/countries"),api.get<PlanDto[]>("/subscriptions/plans"),api.get<PaymentTransactionDto[]>("/subscriptions/transactions"),api.get<{aiMode:"mock"|"openai"}>("/health/ready")]);this.subscription=subscription.data;this.history=records.data.items;this.analytics=analytics.data;this.countries=countries.data;this.plans=plans.data;this.transactions=transactions.data;this.aiMode=health.data.aiMode;this.apiOnline=true;this.initialized=true;}catch(cause){if(isNetworkError(cause))this.apiOnline=false;throw cause;}finally{this.loading=false;}},
    selectFile(file:File){if(this.previewUrl.startsWith("blob:"))URL.revokeObjectURL(this.previewUrl);this.file=file;this.previewUrl=URL.createObjectURL(file);this.scanRequestKey=crypto.randomUUID();this.scan=null;},
    clearFile(){if(this.previewUrl.startsWith("blob:"))URL.revokeObjectURL(this.previewUrl);this.file=null;this.previewUrl="";this.scanRequestKey="";},
    async analyze(){if(!this.file)throw new Error("Choose a photo first");const form=new FormData();form.append("image",this.file);form.append("countryCode",this.selectedCountryCode);const key=this.scanRequestKey||crypto.randomUUID();this.scanRequestKey=key;try{this.scan=(await api.post<ScanDto>("/scans",form,{headers:{"Idempotency-Key":key}})).data;this.subscription=(await api.get<SubscriptionDto>("/subscriptions/current")).data;return this.scan;}catch(cause){this.scanRequestKey=crypto.randomUUID();if(isNetworkError(cause))this.apiOnline=false;throw cause;}},
    async loadScan(id:string){this.scan=(await api.get<ScanDto>(`/scans/${id}`)).data;if(this.scan.thumbnailUrl&&!this.previewUrl){const image=await api.get<Blob>(apiRelativePath(this.scan.thumbnailUrl),{responseType:"blob"});this.previewUrl=URL.createObjectURL(image.data);}return this.scan;},
    async accept(){if(!this.scan)throw new Error("No analyzed scan is available to accept");const {data}=await api.post<{wasteRecordId:string;record:WasteRecordDto}>(`/scans/${this.scan.id}/decision`,{decision:"ACCEPT"});this.record=data.record;await this.refreshInsights();return this.record;},
    async reject(reasonCode="INCORRECT_IDENTIFICATION",comment?:string){if(!this.scan)throw new Error("No analyzed scan is available to reject");return (await api.post<{message:string}>(`/scans/${this.scan.id}/decision`,{decision:"REJECT",reasonCode,comment})).data;},
    async refreshInsights(){const [records,analytics]=await Promise.all([api.get<{items:WasteRecordDto[]}>("/waste-records?pageSize=100"),api.get<AnalyticsDto>("/analytics/summary")]);this.history=records.data.items;this.analytics=analytics.data;},
    async loadRecord(id:string){const cached=this.history.find((item)=>item.id===id);this.record=cached ?? (await api.get<WasteRecordDto>(`/waste-records/${id}`)).data;if(this.record.thumbnailUrl&&!this.previewUrl){const image=await api.get<Blob>(apiRelativePath(this.record.thumbnailUrl),{responseType:"blob"});this.previewUrl=URL.createObjectURL(image.data);}return this.record;},
    async updateWeight(grams:number){if(!this.record)throw new Error("No record is selected");this.record=(await api.patch<WasteRecordDto>(`/waste-records/${this.record.id}/weight`,{grams})).data;const index=this.history.findIndex((item)=>item.id===this.record?.id);if(index>=0)this.history[index]=this.record;this.analytics=(await api.get<AnalyticsDto>("/analytics/summary")).data;return this.record;},
    async deleteRecord(id:string){await api.delete(`/waste-records/${id}`);if(this.record?.id===id)this.record=null;await this.refreshInsights();},
    async checkout(planCode:"PLUS"|"HOUSEHOLD",paymentMethodToken:"tok_demo_visa"|"tok_demo_declined"="tok_demo_visa"){const {data}=await api.post<{subscription:SubscriptionDto;transaction:PaymentTransactionDto}>("/subscriptions/fake-checkout",{planCode,paymentMethodToken});this.subscription=data.subscription;this.transactions.unshift(data.transaction);return data;},
    async upgradePlus(){return this.checkout("PLUS");},
    async switchToFree(){this.subscription=(await api.post<SubscriptionDto>("/subscriptions/switch-to-free")).data;},
    clearPrivateState(){this.clearFile();this.$reset();},
  },
});
