import type { IdentificationResult } from "@resort/contracts";
import { describe,expect,it } from "vitest";
import { RULE_SET_VERSION,RuleEngine } from "../src/rule.engine";

const identified=(overrides:Partial<IdentificationResult>):IdentificationResult=>({primaryObject:"Yogurt cup",isPackaging:true,packagingType:"CUP",packagingState:"EMPTY",materials:[{material:"PP plastic",proportion:"PRIMARY",confidence:.92}],visibleSymbols:[{code:"PP_5",rawText:"PP 5",confidence:.9}],hazardSignals:["NONE"],estimatedWeightGrams:25,weightConfidence:.5,overallConfidence:.88,uncertainties:[],retakeAdvice:null,...overrides});
const factor={id:"factor",kgCo2ePerTonne:4.65358,methodologyVersion:"test-factor-v1",boundary:"Disposal proxy only"};

describe("German deterministic rule engine",()=>{
  it("routes lightweight PP packaging to the yellow bin without an AI route",()=>{const engine=new RuleEngine();const identification=identified({});const sorted=engine.resolve(identification);const record=engine.buildRecord("scan-1",identification,sorted,factor);expect(sorted.binLabel).toBe("Yellow bin or sack");expect(record.ruleSetVersion).toBe(RULE_SET_VERSION);expect(record.estimatedDisposalCo2eKg).toBeCloseTo((25/1_000_000)*4.65358);});
  it("routes a banana peel to bio collection",()=>{const result=new RuleEngine().resolve(identified({primaryObject:"Banana peel",isPackaging:false,packagingType:"OTHER",materials:[{material:"Organic food waste",proportion:"PRIMARY",confidence:.97}],visibleSymbols:[],estimatedWeightGrams:45,overallConfidence:.98}));expect(result.category).toBe("ORGANIC");expect(result.binLabel).toContain("Bio bin");expect(result.disposalRoute).toBe("BIO_BIN_OR_COMPOST");});
  it("routes dangerous paint to specialist collection before packaging rules",()=>{const result=new RuleEngine().resolve(identified({primaryObject:"Partly full paint tin",isPackaging:false,packagingType:"CAN",packagingState:"PARTLY_FULL",materials:[{material:"Paint and metal",proportion:"PRIMARY",confidence:.91}],hazardSignals:["TOXIC"],visibleSymbols:[],estimatedWeightGrams:900,overallConfidence:.93}));expect(result.category).toBe("HAZARDOUS_WASTE");expect(result.disposalRoute).toBe("HAZARDOUS_WASTE_COLLECTION_POINT");expect(result.preparationSteps.join(" ")).toContain("Do not");});
  it("uses local guidance rather than a default bin at low confidence",()=>{const result=new RuleEngine().resolve(identified({primaryObject:"Unclear household item",isPackaging:false,packagingType:"OTHER",materials:[{material:"Unknown mixed material",proportion:"PRIMARY",confidence:.42}],visibleSymbols:[],overallConfidence:.5,uncertainties:["Obscured"]}));expect(result.category).toBe("LOCAL_GUIDANCE_REQUIRED");expect(result.disposalRoute).toBe("CHECK_LOCAL_GUIDANCE");});
});
